name: Build, deploy, and test Python app to Azure Web App - UniversityPlacement

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DB87EF9E88CF4D96A9FC979CDD8FA3BF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_362637ECCEDB4E55A2840B07F080319E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FB9A954A538E4F6E94B9A9D950B2A365 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'UniversityPlacement'
          slot-name: 'production'

  test:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Ensure compatibility with Newman

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman tests
        run: |
          newman run Univeristy\ Placement\ Cell\ TestCases.postman_collection.json -e Uni\ Port.postman_environment.json -r cli,html --reporter-html-export newman-report.html

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: newman-report
          path: newman-report.html
